import React from 'react';
import { 
  Code, 
  Play, 
  Download, 
  Search, 
  Layout, 
  MessageSquare, 
  FileCode, 
  Settings, 
  ChevronRight, 
  ChevronDown,
  RefreshCw,
  Globe,
  Monitor,
  Smartphone,
  CheckCircle,
  XCircle,
  Menu,
  X,
  Save,
  FolderOpen,
  Trash2,
  Plus,
  Bug,
  Archive,
  Share2,
  Link,
  ExternalLink,
  Copy,
  Twitter,
  Linkedin,
  GitBranch,
  GitCommit,
  GitPullRequest,
  PlusCircle,
  MinusCircle,
  Clock,
  History,
  Image,
  Upload,
  Database,
  Server,
  HardDrive,
  Rocket,
  CloudUpload,
  Zap,
  Github,
  ListTodo,
  Edit2,
  Network,
  ShieldCheck,
  Layers,
  FilePlus
} from 'lucide-react';

export const Icons = {
  Code,
  Play,
  Download,
  Search, 
  Layout,
  MessageSquare,
  File: FileCode,
  Settings,
  ChevronRight, 
  ChevronDown,
  Refresh: RefreshCw,
  Globe,
  Monitor,
  Mobile: Smartphone,
  Success: CheckCircle,
  Error: XCircle,
  Menu,
  Close: X,
  Save,
  Folder: FolderOpen,
  Trash: Trash2,
  Plus,
  Bug,
  Archive,
  Share: Share2,
  Link,
  ExternalLink,
  Copy,
  Twitter,
  Linkedin,
  GitBranch,
  GitCommit,
  GitMerge: GitPullRequest,
  PlusCircle,
  MinusCircle,
  Clock,
  History,
  Image,
  Upload,
  Database,
  Server,
  HardDrive,
  Rocket,
  CloudUpload,
  Zap,
  Github,
  ListTodo,
  Edit: Edit2,
  Network,
  Audit: ShieldCheck,
  Architect: Layers,
  FilePlus
};

export const FileIcon = ({ fileName, className = "w-4 h-4" }: { fileName: string, className?: string }) => {
  const ext = fileName.split('.').pop()?.toLowerCase();
  
  const iconMap: Record<string, string> = {
    html: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg',
    css: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg',
    js: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg',
    jsx: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg',
    ts: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg',
    tsx: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg',
    py: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg',
    json: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/json/json-original.svg',
    md: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/markdown/markdown-original.svg',
    rb: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/ruby/ruby-original.svg',
    php: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/php/php-original.svg',
    java: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/java/java-original.svg',
    go: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/go/go-original.svg',
    c: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/c/c-original.svg',
    cpp: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/cplusplus/cplusplus-original.svg',
    cs: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/csharp/csharp-original.svg',
    rs: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/rust/rust-original.svg',
    sql: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mysql/mysql-original.svg',
    xml: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/xml/xml-original.svg',
    yml: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/yaml/yaml-original.svg',
    yaml: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/yaml/yaml-original.svg',
    scss: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/sass/sass-original.svg',
    sass: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/sass/sass-original.svg',
    vue: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vuejs/vuejs-original.svg',
    swift: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/swift/swift-original.svg',
    kt: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/kotlin/kotlin-original.svg',
    dart: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/dart/dart-original.svg',
    toml: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tomcat/tomcat-original.svg', // Fallback for TOML
  };

  if (ext && iconMap[ext]) {
    return <img src={iconMap[ext]} alt={ext} className={`${className} shrink-0 object-contain`} />;
  }
  
  return <Icons.File className={`${className} text-gray-400 shrink-0`} />;
};